[package]
name = "macro_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed_mongo_query_macro = { path = "../typed_mongo_query_macro" }
typed_mongo_query = { path = "../typed_mongo_query" }
